language: python
notifications:
    email: false
env:
    global:
python:
    - 2.7
install:
    - pip install zc.buildout
    - buildout init
    - python setup.py install
    - pip install -r tests/requirements.txt
script:
    make test
after_success:
    coveralls

