language: python
notifications:
    email: false
env:
    global:
python:
    - 2.7
install:
    - buildout init
    - python setup.py install
    - pip install -r tests/requirements.txt
script:
    make test
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls

